/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package scene;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Product;
import repository.ProductRepositoryImpl;
import scene.AdminScene;

/**
 *
 * @author Manh
 */
public class AddProductScene extends javax.swing.JPanel {
    private ProductRepositoryImpl productRepositoryImpl;
    private AdminScene admin;
    /**
     * Creates new form AddProductScene
     */
    public AddProductScene(AdminScene admin) {
        
        initComponents();
        productRepositoryImpl = new ProductRepositoryImpl();
        this.admin = admin;
    }

    public void clearDetails(){
        textMaSP.setText("");
        textTenSP.setText("");
        textGia.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textMaSP = new javax.swing.JTextField();
        textTenSP = new javax.swing.JTextField();
        textGia = new javax.swing.JTextField();
        boxLoai = new javax.swing.JComboBox<>();
        addingBtn = new javax.swing.JButton();

        jLabel1.setText("Mã sản phẩm :");

        jLabel2.setText("Tên sản phẩm : ");

        jLabel3.setText("Giá : ");

        jLabel4.setText("Loại : ");

        boxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồ Uống", "Đồ Ăn", " ", " ", " " }));

        addingBtn.setText("Thêm");
        addingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textMaSP)
                            .addComponent(textTenSP)
                            .addComponent(textGia)
                            .addComponent(boxLoai, 0, 236, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(addingBtn)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(addingBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addingBtnActionPerformed
        // TODO add your handling code here:
        String id = textMaSP.getText();
        String name = textTenSP.getText();
        String gia = textGia.getText();
        String loai = boxLoai.getSelectedItem().toString();
        if(id.length() > 0 && name.length() > 0 && gia.length() > 0)
        {
            if(gia.matches("\\d+"))
            {
                double giaBan = Float.parseFloat(gia);
                Product pd = new Product(id, name, giaBan, loai);
                productRepositoryImpl.addProduct(pd);
                clearDetails();
                javax.swing.JDialog dialog = (javax.swing.JDialog)javax.swing.SwingUtilities.getWindowAncestor(this);
                dialog.dispose();
                admin.addProductToTable(pd);
           
            
           
            
            
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(textGia,"Giá chỉ có thể là số");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(textMaSP, "Không được bỏ trống thông tin");
        }
        
    }//GEN-LAST:event_addingBtnActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addingBtn;
    private javax.swing.JComboBox<String> boxLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textGia;
    private javax.swing.JTextField textMaSP;
    private javax.swing.JTextField textTenSP;
    // End of variables declaration//GEN-END:variables

}
