package scene;

import AdminViews.UserManager;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import repository.UserRepositoryImpl;
import scene.AdminScene;

public class AddUserScene extends javax.swing.JFrame {
    private UserRepositoryImpl userRepositoryImpl;
    private UserManager userManager; 

    public AddUserScene(UserManager userManager) {
        initComponents();
        this.userManager = userManager;
        userRepositoryImpl = new UserRepositoryImpl();
        this.setLocationRelativeTo(null);
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String ten = txtTen.getText();
        String email = txtEmail.getText();
        String sdt = txtSDT.getText();
        String matKhau = txtMatKhau.getText();
        String diaChi = txtDiaChi.getText();
        String chucVu = (String) comboChucVu.getSelectedItem();
        String gioiTinh = (String) comboGioiTinh.getSelectedItem();
        String caLam = (String) comboCaLam.getSelectedItem();

        User newUser = new User(
            userRepositoryImpl.generateId(),
            ten, email, sdt, matKhau, chucVu, gioiTinh, diaChi, caLam
        );

        boolean success = userRepositoryImpl.add(newUser);

        if (success) {
            JOptionPane.showMessageDialog(this, "Thêm người dùng thành công!");
            userManager.loadUserTable();
            this.dispose(); // đóng popup
        } else {
            JOptionPane.showMessageDialog(this, "Thêm người dùng thất bại!");
        }
    }
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gioiTinh = new javax.swing.ButtonGroup();
        caLamViec = new javax.swing.ButtonGroup();
        tenNV = new javax.swing.JTextField();
        LabelTK = new javax.swing.JLabel();
        LabelMK = new javax.swing.JLabel();
        matKhau = new javax.swing.JPasswordField();
        displayPassword = new javax.swing.JCheckBox();
        inputData = new javax.swing.JButton();
        gtNam = new javax.swing.JRadioButton();
        gtNu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        queQuan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        caSang = new javax.swing.JRadioButton();
        caTrua = new javax.swing.JRadioButton();
        caToi = new javax.swing.JRadioButton();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        chucVu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm nhân viên");

        LabelTK.setText("Nhập tên nhân viên: ");

        LabelMK.setText("Nhập mật khẩu: ");

        displayPassword.setText("Hiện/ Ẩn mật khẩu");
        displayPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPasswordActionPerformed(evt);
            }
        });

        inputData.setText("Nhập vào bảng");
        inputData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataActionPerformed(evt);
            }
        });

        gioiTinh.add(gtNam);
        gtNam.setText("Nam");
        gtNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtNamActionPerformed(evt);
            }
        });

        gioiTinh.add(gtNu);
        gtNu.setText("Nữ");

        jLabel4.setText("Giới tính: ");

        jLabel5.setText("Email:");

        jLabel7.setText("Quê quán:");

        jLabel8.setText("Chức vụ:");

        jLabel9.setText("Ca làm việc");

        caLamViec.add(caSang);
        caSang.setText("Ca sáng");

        caLamViec.add(caTrua);
        caTrua.setText("Ca chiều");

        caLamViec.add(caToi);
        caToi.setText("Ca tối");

        reset.setText("Làm mới");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setText("Số điện thoại:");

        chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER", "ADMIN" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputData)
                        .addGap(18, 18, 18)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caSang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caTrua, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caToi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelMK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayPassword)
                            .addComponent(LabelTK)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gtNu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(matKhau)
                                .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneField))
                            .addComponent(queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LabelTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gtNam)
                    .addComponent(gtNu)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caSang)
                        .addComponent(caTrua)
                        .addComponent(caToi)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputData)
                    .addComponent(reset))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataActionPerformed
        String name = tenNV.getText();
        String password = new String(matKhau.getPassword());
        String mail = email.getText();
        String phone = phoneField.getText();
        String gender = "";
        String hometown = queQuan.getText();
        String position = (String) chucVu.getSelectedItem();
        String workShift = "";

        if (name.isEmpty() || password.isEmpty() || hometown.isEmpty() || position.isEmpty() || phone.isEmpty() || mail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isPasswordValid(password)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ thường, in hoa, số và ký tự đặc biệt!", "Mật khẩu không hợp lệ", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isEmailValid(mail)) {
            JOptionPane.showMessageDialog(this, "Định dạng email không hợp lệ", "Email không hợp lệ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        if (!isPhoneNumberValid(phone)) {
            JOptionPane.showMessageDialog(this, "Định dạng số điện thoại không hợp lệ", "Số điện thoại không hợp lệ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (caSang.isSelected()) {
            workShift = "Ca sáng";
        } else if (caTrua.isSelected()) {
            workShift = "Ca chiều";
        } else if (caToi.isSelected()) {
            workShift = "Ca tối";
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ca làm việc.", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (gtNam.isSelected()) {
            gender = "Nam";
        } else if (gtNu.isSelected()) {
            gender = "Nữ";
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính.", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        User newUser = new User("", name, mail, phone, password, hometown, position, gender, workShift);
        userRepositoryImpl.addUser(newUser);
        adminScene.addUserToTable(newUser);
        clearDetails();
    }//GEN-LAST:event_inputDataActionPerformed

    private void displayPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPasswordActionPerformed
        if (displayPassword.isSelected()) {
            matKhau.setEchoChar((char) 0);
        } else {
            matKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_displayPasswordActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        clearDetails();
    }//GEN-LAST:event_resetActionPerformed

    private void gtNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUserScene().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMK;
    private javax.swing.JLabel LabelTK;
    private javax.swing.ButtonGroup caLamViec;
    private javax.swing.JRadioButton caSang;
    private javax.swing.JRadioButton caToi;
    private javax.swing.JRadioButton caTrua;
    private javax.swing.JComboBox<String> chucVu;
    private javax.swing.JCheckBox displayPassword;
    private javax.swing.JTextField email;
    private javax.swing.ButtonGroup gioiTinh;
    private javax.swing.JRadioButton gtNam;
    private javax.swing.JRadioButton gtNu;
    private javax.swing.JButton inputData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField matKhau;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField queQuan;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tenNV;
    // End of variables declaration//GEN-END:variables
}
