package scene;

import model.User;

/**
 *
 * @author admin
 */
public class EditUserForm extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form EditUserForm
     */
    public EditUserForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public EditUserForm(User user) {
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        buttonGroup_gioiTinh = new javax.swing.ButtonGroup();
        buttonGroup_caLam = new javax.swing.ButtonGroup();
        LableHeader = new javax.swing.JLabel();
        jLabel_Ten = new javax.swing.JLabel();
        jTextField_TenNhanVien = new javax.swing.JTextField();
        jLable_Email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jTextField_sdt = new javax.swing.JTextField();
        jLabel_Sdt = new javax.swing.JLabel();
        jLable_matKhau = new javax.swing.JLabel();
        jTextField_matKhau = new javax.swing.JTextField();
        jLabel_queQuan = new javax.swing.JLabel();
        jTextField_queQuan = new javax.swing.JTextField();
        jLabel_chucVu = new javax.swing.JLabel();
        jLable_gioiTinh = new javax.swing.JLabel();
        jLabel_CaLamViec = new javax.swing.JLabel();
        jButton_Update = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jComboBox_chucVu = new javax.swing.JComboBox<>();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jRadioButton_nu = new javax.swing.JRadioButton();
        jRadioButton_CaSang = new javax.swing.JRadioButton();
        jRadioButton_caTrua = new javax.swing.JRadioButton();
        jRadioButton_caToi = new javax.swing.JRadioButton();

        jLabel3.setText("Tên Nhân Viên");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chỉnh sửa thông tin");

        LableHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LableHeader.setText(" EDIT USER");

        jLabel_Ten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Ten.setText("Tên Nhân Viên");

        jLable_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLable_Email.setText("Email");

        jLabel_Sdt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Sdt.setText("Số Điện Thoại");

        jLable_matKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLable_matKhau.setText("Mật Khẩu");

        jLabel_queQuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_queQuan.setText("Quê Quán");

        jLabel_chucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_chucVu.setText("Chức Vụ");

        jLable_gioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLable_gioiTinh.setText("Giới Tính");

        jLabel_CaLamViec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_CaLamViec.setText("Ca Làm Việc");

        jButton_Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jComboBox_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER", "ADMIN" }));

        buttonGroup_gioiTinh.add(jRadioButton_nam);
        jRadioButton_nam.setText("Nam");

        buttonGroup_gioiTinh.add(jRadioButton_nu);
        jRadioButton_nu.setText("Nữ");

        buttonGroup_caLam.add(jRadioButton_CaSang);
        jRadioButton_CaSang.setText("Ca Sáng ");

        buttonGroup_caLam.add(jRadioButton_caTrua);
        jRadioButton_caTrua.setText("Ca Trưa");

        buttonGroup_caLam.add(jRadioButton_caToi);
        jRadioButton_caToi.setText("Ca Tối");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLable_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField_matKhau))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField_sdt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLable_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField_email))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Update)
                        .addGap(65, 65, 65)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLable_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_CaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_queQuan)
                            .addComponent(jComboBox_chucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_CaSang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_caTrua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_caToi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Ten)
                    .addComponent(jTextField_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLable_Email)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Sdt)
                    .addComponent(jTextField_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLable_matKhau)
                    .addComponent(jTextField_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_queQuan)
                    .addComponent(jTextField_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_chucVu)
                    .addComponent(jComboBox_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLable_gioiTinh)
                    .addComponent(jRadioButton_nam)
                    .addComponent(jRadioButton_nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CaLamViec)
                    .addComponent(jRadioButton_CaSang)
                    .addComponent(jRadioButton_caTrua)
                    .addComponent(jRadioButton_caToi))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed

        String tenNhanVien = jTextField_TenNhanVien.getText().trim();
        String email = jTextField_email.getText().trim();
        String sdt = jTextField_sdt.getText().trim();
        String matKhau = jTextField_matKhau.getText().trim();
        String queQuan = jTextField_queQuan.getText().trim();
        String chucVu = (String) jComboBox_chucVu.getSelectedItem();

        String gioiTinh = "";
        if (jRadioButton_nam.isSelected()) {
            gioiTinh = "Nam";
        } else if (jRadioButton_nu.isSelected()) {
            gioiTinh = "Nữ";
        }

        String caLam = "";
        if (jRadioButton_CaSang.isSelected()) {
            caLam = "Ca Sáng";
        } else if (jRadioButton_caTrua.isSelected()) {
            caLam = "Ca Trưa";
        } else if (jRadioButton_caToi.isSelected()) {
            caLam = "Ca Tối";
        }

        // Kiểm tra đầu vào 
        if (tenNhanVien.isEmpty() || email.isEmpty() || sdt.isEmpty() || matKhau.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc.");
            return;
        }

        //Kiem tra Email
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if (!email.matches(emailRegex)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Email không hợp lệ.");
            return;
        }

        // In ra để kiểm tra
        System.out.println("Tên: " + tenNhanVien);
        System.out.println("Email: " + email);
        System.out.println("SĐT: " + sdt);
        System.out.println("Mật khẩu: " + matKhau);
        System.out.println("Quê quán: " + queQuan);
        System.out.println("Chức vụ: " + chucVu);
        System.out.println("Giới tính: " + gioiTinh);
        System.out.println("Ca làm: " + caLam);

        javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có muốn hủy thay đổi?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_jButton_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LableHeader;
    private javax.swing.ButtonGroup buttonGroup_caLam;
    private javax.swing.ButtonGroup buttonGroup_gioiTinh;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_chucVu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_CaLamViec;
    private javax.swing.JLabel jLabel_Sdt;
    private javax.swing.JLabel jLabel_Ten;
    private javax.swing.JLabel jLabel_chucVu;
    private javax.swing.JLabel jLabel_queQuan;
    private javax.swing.JLabel jLable_Email;
    private javax.swing.JLabel jLable_gioiTinh;
    private javax.swing.JLabel jLable_matKhau;
    private javax.swing.JRadioButton jRadioButton_CaSang;
    private javax.swing.JRadioButton jRadioButton_caToi;
    private javax.swing.JRadioButton jRadioButton_caTrua;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JRadioButton jRadioButton_nu;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_TenNhanVien;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_matKhau;
    private javax.swing.JTextField jTextField_queQuan;
    private javax.swing.JTextField jTextField_sdt;
    // End of variables declaration//GEN-END:variables
}
